Services/TableService.php

fix on filters TYPE_IN and TYPE_NOT_IN

---

Resources/public/js/KilikTable.js

fix safari bug

---

Command/GenerateCommand.php
Generator/ControllerGenerator.php
README.md
Resources/skeleton/_list.html.twig.twig
Resources/skeleton/controller.php.twig
Resources/skeleton/list.html.twig.twig
Resources/views/layout.html.twig
composer.json

This branch add a table generator (controller + template generation).

Add table generator

---

Command/GenerateCommand.php
Generator/ControllerGenerator.php
Resources/skeleton/controller.php.twig
Resources/skeleton/list.html.twig.twig

19 error table generator

---

Resources/config/services.yml
Resources/views/_columnCell.html.twig
Resources/views/_columnCellNoTable.html.twig
Resources/views/_columnFilter.html.twig
Resources/views/_columnFilterNoTable.html.twig
Resources/views/_columnName.html.twig
Resources/views/_columnNameNoTable.html.twig
Resources/views/_condensedTable.html.twig
Resources/views/_defaultTable.html.twig
Resources/views/_defaultTableAlt.html.twig
Resources/views/_formLeftNoTable.html.twig
Resources/views/_pagination.html.twig
Resources/views/_paginationNumbers.html.twig
Resources/views/_paginationNumbersIcons.html.twig
Resources/views/_rowsPerPage.html.twig
Resources/views/_setup.html.twig
Resources/views/_stats.html.twig
Services/AbstractTableService.php

fix templates path (see #24 for more informations)

---

Resources/public/js/KilikTable.js

Optimization : abort current ajax query requesting a new one

---

Components/Filter.php
Components/FilterCheckbox.php
Components/FilterSelect.php
Services/AbstractTableService.php

With this modification it's now possible to use any symfony FormType has a filter this make
filter more flexible and configurable

Edit Filter to use symfony FormType

---

Resources/public/js/KilikTable.js

The filter loading didn't work for radio input now it does

Fix filter loading from localStorage

---

Resources/public/js/KilikTable.js

This allow the user to access the request data without redefining doReload

Add the dataRaw to the afterReload function

---

Components/Filter.php

Fix issue when filtering a date column with time (e.g. 2018-12-10 15:44)

Fix filter date data formater

---

Services/TableService.php

If there is an input multiple we handle it and allow to use the queryPartBuilder.

Allow the Filter to have input multiple

---

Components/AbstractTable.php
Resources/views/_blocks.html.twig
Resources/views/_columnCell.html.twig
Resources/views/_columnCellNoTable.html.twig
Resources/views/_columnFilter.html.twig
Resources/views/_columnFilterNoTable.html.twig
Resources/views/_columnName.html.twig
Resources/views/_columnNameNoTable.html.twig

- mass action is now handled from filter row
- scope's attribute are setted to "col" for each heading column
- data-label attribute has been added into each column to specify the data meaning, and to help building responsive css
- a table title can be added (that will add the <caption> markup)

add properties to make table more accessible

---

src/Components/Column.php
src/Services/AbstractTableService.php

It will be interesting to be able to set column export name, instead of column name

set export column name

---

src/Resources/config/services.yml

I forgot an @ in the previous PR

Fix missing @ for service kilik_table_api

---

src/Services/TableService.php

Here my proposition to fix the count row, this way it will only change the behavior if we have a custom output walker, which should allow a larger support of the different rdbms.
Note that the native query is very similar to what is done by the Paginator with the CountOutputWalker except that this way we won't overwrite user custom output walker

Fix rows count when using Doctrine custom output walker

---

src/Components/Column.php
src/Resources/public/css/KilikTable.css
src/Resources/public/js/KilikTable.js
src/Resources/translations/messages.en.yml
src/Resources/translations/messages.es.yml
src/Resources/translations/messages.fr.yml
src/Resources/translations/messages.nl.yml
src/Resources/views/_defaultTable.html.twig
src/Resources/views/_defaultTableAlt.html.twig
src/Resources/views/_defaultTableSimple.html.twig
src/Resources/views/theme/dark4/tables/alternative.html.twig
src/Resources/views/theme/dark4/tables/default.html.twig
src/Services/TableService.php

* Method displayTotal replaced by useTotal
* Apply callback on total cells
* Fix show/hide columns
* Improve style

fix total usage

---

composer.json
composer.lock
prepare-tests.sh
run-tests.sh
scripts/composer.sh
src/DependencyInjection/Configuration.php

For fix deprecated Symfony 5.4

Fix kilikTable for Symfony 5.4

---

src/Resources/public/css/KilikTable.css
src/Resources/public/js/KilikTable.js

fill filter if not empty

---

src/Resources/public/js/KilikTable.js

When we have filter with a select multiple the filter wasn't save correctly in the localStorage

Fix save and loading of fields select multiple

---

composer.json
prepare-tests.sh
run-tests.sh

add php 8.3 support and Symfony 7

add php 8.3 support and Symfony 7
